# cd.yaml
# Azure DevOps Pipeline for Continuous Deployment of an online documentation wiki

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCS_DIR: 'docs'
  BUILD_ARTIFACT: 'wiki-site'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install mkdocs mkdocs-material
    displayName: 'Install MkDocs and dependencies'

  - script: |
      mkdocs build --clean
    displayName: 'Build Wiki Site'

  - script: |
      git config --global user.email "buildagent@example.com"
      git config --global user.name "Azure DevOps Build Agent"
      git fetch origin
      git checkout gh-pages || git checkout --orphan gh-pages
      rm -rf *
      cp -r site/* .
      git add .
      git commit -m "Update site [skip ci]" || echo "No changes to commit"
      git push origin gh-pages
    displayName: 'Publish to GitHub Pages'
    env:
      GITHUB_TOKEN: $(GH_TOKEN)

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'site'
      ArtifactName: '$(BUILD_ARTIFACT)'
    displayName: 'Publish Wiki Site Artifact'